# ==========================================================================
# Build system
# ==========================================================================

CFLAGS += -mno-outline-atomics
LDFLAGS += --no-warn-rwx-segments # Eventually we should remove this option and figure out what the issue actually is
