obj-y += asm/ \
		init.o \
		main.o \
		mwait.o \
		numa.o \
		smp.o \
		early_mem.o \
		shutdown.o  \
		arch.o \
		irq.o \
		fpu.o \
                idt.o \
                msr.o \
                mtrr.o \
                cpuid.o \
                thread.o

obj-$(NAUT_CONFIG_REAL_MODE_INTERFACE) += realmode.o
