obj-y += asm/ \
	 arch.o \
	 init.o \
	 main.o \
	 smp.o \
	 early_mem.o \
	 sbi.o \
	 trap.o \
	 monitor.o \
	 paging.o \
	 shutdown.o \
	 irq.o \
	 idt.o \
         hlic.o

# KJH - I'm going to leave the idt.c stuff alone for now because the focus is ARM64 beandip,
# but I'd like to go back and patch that to work with interrupt system
