obj-y += asm/ \
	init.o \
	irq.o \
	arch.o \
	fpu.o \
	setjmp.o \
	excp.o \
	smp.o \
	timer.o \
	psci.o \
	paging.o \

obj-$(NAUT_CONFIG_GIC_VERSION_2) += gicv2.o

obj-$(NAUT_CONFIG_GIC_VERSION_3) += gicv3.o

